### ISSUE TITLE
Consider changing the default timeout

### ISSUE THREAD

**Issue by The-Compiler** [benapetr/stikkit#2]
I just discovered stikkit has a default timeout of 60 minutes if nothing else is given. This made me loose many pastes I probably still needed :(

This is also not mentioned in `--help`, but either way - I'd expect an unlimited paste if I don't say otherwise.

**Comment by benapetr** [comment]
ah, yes that should be configurable I will try to fix that however I am not sure how to ensure unlimited paste, perhaps parameter needs 0?

**Comment by The-Compiler** [comment]
Yes, 0 means unlimited.

**Comment by benapetr** [comment]
this fixed it: https://github.com/benapetr/stikkit/commit/5fb127f912b1518293f26c7e36dccce39f5289f2

but I am still not sure if not using the parameter would do that, maybe it just uses the default expiry time? I don't know

**Comment by benapetr** [comment]
well, 0 in my code will cause the parameter for expiry time to be completely removed from API url

**Comment by The-Compiler** [comment]
That works as well and does the same. That probably would be a reasonable default. All parameters except `text` are optional in the API.
